---
- name: Upload files to S3
  hosts: localhost
  gather_facts: no
  
  vars:
    aws_region: 'eu-central-1'
    s3_bucket: 'demo-cloudvests-storage'
    directory_path: '/upload'
    s3_key: 'files.tar.gz'
  
  tasks:
    - name: Compress directory
      archive:
        path: "{{ directory_path }}"
        dest: "{{ s3_key }}"
        format: gz
  
    - name: Upload file to S3
      shell: "aws s3 cp {{ s3_key }} s3://{{ s3_bucket }}/{{ s3_key }} --region {{ aws_region }}"
